version: '3.8'
services:
  nginx-proxy:
    container_name: 'nginx-proxy'
    image: jwilder/nginx-proxy:alpine
    restart: unless-stopped
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - application
    ports:
      - 80:80
      - 443:443

networks:
  application:
    external: true
    name: nginx-net