version: '3.8'
services:
  code-server:
    image: linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - PASSWORD=123 #optional
      - SUDO_PASSWORD=123 #optional
      - VIRTUAL_HOST=code.localhost
      #- LETSENCRYPT_HOST=code.localhost
      #- VIRTUAL_PROTO=https
      - VIRTUAL_PORT=8443
    volumes:
      - config:/config
      - workspace:/workspace
    ports:
        - 8443:8443
    restart: unless-stopped
    networks:
      - application

volumes: 
  config:
    name: code-config
  workspace:
    name: code-workspace

networks:
  application:
    external: 
      name: nginx-net