version: '3.8'
services:
  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.lab-casa.tk
    networks: 
      - application

networks:
  application:
    external: 
      name: nginx-net
