version: "3.8"
services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - UMASK_SET=022 #optional
      - VIRTUAL_HOST=radarr.localhost
    volumes:
      - config-radarr:/config
      - movies:/movies
      - ../qbittorrent/downloads/movies:/downloads
    # ports:
    #   - 7878:7878
    restart: unless-stopped
    networks: 
      - application

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - UMASK_SET=022 #optional
      - VIRTUAL_HOST=sonarr.localhost
      - VIRTUAL_PORT=8989
    volumes:
      - config-sonarr:/config
      - tvseries:/tv
      - ../qbittorrent/downloads/tvshows:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    networks: 
      - application

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Sao_Paulo
      - AUTO_UPDATE=true #optional
      #- RUN_OPTS=<run options here> #optional
      - VIRTUAL_HOST=jackett.localhost
    volumes:
      - config-jackett:/config
      - ../qbittorrent/downloads:/downloads
    # ports:
    #   - 9117:9117
    restart: unless-stopped
    networks: 
      - application

volumes: 
  config-radarr: 
    name: radarr-config
  config-jackett: 
    name: radarr-jackett
  config-sonarr:
    name: sonarr-config
  movies: 
    name: radarr-movies
  tvseries:
    name: sonarr-tvseries

networks:
  application:
    external: 
        name: nginx-net