version: "3.8"
services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - UMASK_SET=022 #optional
      - VIRTUAL_HOST=radarr.localhost
    volumes:
      - config-radarr:/config
      - movies:/movies
      - ../qbittorrent/downloads:/downloads
    # ports:
    #   - 7878:7878
    restart: unless-stopped
    networks: 
      - application

  medusa:
    image: linuxserver/medusa
    container_name: medusa
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - VIRTUAL_HOST=medusa.localhost
      - VIRTUAL_PORT=8081
    volumes:
      - config-medusa:/config
      - tv:/tv
      - ../qbittorrent/downloads:/downloads
    # ports:
    #   - 8081:8081
    restart: unless-stopped
    networks: 
      - application
  
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Sao_Paulo
      - AUTO_UPDATE=true #optional
      #- RUN_OPTS=<run options here> #optional
      - VIRTUAL_HOST=jackett.localhost
    volumes:
      - config-jackett:/config
      - ../qbittorrent/downloads:/downloads
    # ports:
    #   - 9117:9117
    restart: unless-stopped
    networks: 
      - application

volumes: 
  config-radarr: 
      name: radarr-config
  config-jackett: 
      name: radarr-jackett
  config-medusa: 
      name: radarr-medusa
  movies: 
      name: radarr-movies
  tv: 
      name: medusa-tv

networks:
  application:
    external: 
        name: nginx-net